dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - "$HOME/.opam"
before_cache:
- rm -rf ~/.opam/log/
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib
env:
  global:
  - NJOBS=2
  - COMPILER="system"
  - CAMLP5_VER="6.14"
  - NATIVE_COMP="yes"
  - COQ_DEST="-local"
  matrix:
  - TEST_TARGET="test-suite" COMPILER="4.02.3+32bit"
  - TEST_TARGET="validate"                           TW="travis_wait"
  - TEST_TARGET="validate"   COMPILER="4.02.3+32bit" TW="travis_wait"
  - TEST_TARGET="ci-bedrock-src"
  - TEST_TARGET="ci-bedrock-facade"
  - TEST_TARGET="ci-color"
  - TEST_TARGET="ci-compcert"
  - TEST_TARGET="ci-coquelicot"
  - TEST_TARGET="ci-geocoq"
  - TEST_TARGET="ci-fiat-crypto"
  - TEST_TARGET="ci-fiat-parsers"
  - TEST_TARGET="ci-flocq"
  - TEST_TARGET="ci-formal-topology"
  - TEST_TARGET="ci-hott"
  - TEST_TARGET="ci-iris-coq"
  - TEST_TARGET="ci-math-classes"
  - TEST_TARGET="ci-math-comp"
  - TEST_TARGET="ci-sf"
  - TEST_TARGET="ci-unimath"
  - TEST_TARGET="ci-vst"
matrix:
  allow_failures:
  - env: TEST_TARGET="ci-geocoq"
  include:
  - env:
    - TEST_TARGET="test-suite"
    - EXTRA_CONF="-coqide opt -with-doc yes"
    - EXTRA_OPAM="lablgtk-extras hevea"
    addons:
      apt:
        sources:
        - avsm
        packages: &1
        - opam
        - aspcud
        - libgtk2.0-dev
        - libgtksourceview2.0-dev
        - texlive-latex-base
        - texlive-latex-recommended
        - texlive-latex-extra
        - texlive-math-extra
        - texlive-fonts-recommended
        - texlive-fonts-extra
        - latex-xcolor
        - ghostscript
        - transfig
        - imagemagick
        - tipa
  - env:
    - TEST_TARGET="test-suite"
    - COMPILER="4.04.1"
    - CAMLP5_VER="6.17"
    - EXTRA_CONF="-coqide opt -with-doc yes"
    - EXTRA_OPAM="lablgtk-extras hevea"
    addons:
      apt:
        sources:
        - avsm
        packages: *1
  - env:
    - TEST_TARGET="coqocaml"
    - EXTRA_CONF="-coqide opt -warn-error"
    - EXTRA_OPAM="lablgtk-extras hevea"
    - BUILD_TARGET="clean"
    addons:
      apt:
        sources:
        - avsm
        packages: &2
        - opam
        - aspcud
        - libgtk2.0-dev
        - libgtksourceview2.0-dev
  - env:
    - TEST_TARGET="coqocaml"
    - COMPILER="4.04.1"
    - CAMLP5_VER="6.17"
    - EXTRA_CONF="-coqide opt -warn-error"
    - EXTRA_OPAM="lablgtk-extras hevea"
    - BUILD_TARGET="clean"
    addons:
      apt:
        sources:
        - avsm
        packages: *2
  - os: osx
    env:
    - TEST_TARGET=""
    - COMPILER="system"
    - CAMLP5_VER="6.17"
    - NATIVE_COMP="no"
    - EXTRA_CONF="-coqide opt"
    - OUTDIR="_install"
    - COQ_DEST="-prefix _install"
    - EXTRA_OPAM="lablgtk-extras"
    before_install:
    - brew update
    - brew install opam gtk+ expat gtksourceview libxml2 gdk-pixbuf python3
    - pip3 install macpack
    before_deploy:
    - DMGDIR="_dmg"
    - VERSION=$(sed -n -e '/^let coq_version/ s/^[^"]*"\([^"]*\)"$/\1/p' configure.ml)
    - APP=bin/CoqIDE_${VERSION}.app
    - make -j ${NJOBS} ${APP}
    - make OLDROOT=${OUTDIR} COQINSTALLPREFIX=${APP}/Contents/Resources/ install-coq
      install-ide-toploop
    - codesign -f -s - ${APP}
    - mkdir -p ${DMGDIR}
    - ln -sf /Applications ${DMGDIR}/Applications
    - cp -r ${APP} ${DMGDIR}
    - mkdir -p _build
    - hdiutil create -imagekey zlib-level=9 -volname CoqIDE_${VERSION} -srcfolder
      ${DMGDIR} -ov -format UDZO build/CoqIDE_${VERSION}.dmg
    deploy:
      provider: bintray
      user: maximedenes
      file: bintray.json
      key:
        secure: "ul0A2TtKukg69VUWeK6ZUG4PqFu9S7YTBu85Stdn9xTQnNo7qxvdiG3HZEkmXehw9Su4UljZ+e1KcOhl7gaRKUbXoxvCDf9sRBKSqABpB3jZzj18t5t2DdqSNB/9FTMBPRiaxyZw0COEH8DHHkTtaDw6nmSvkN8E+8F91TX2ACC2bt1NX9Xr7D1ND48W0bRVb2tw6WUjh56buGAQIxkgJxjNhRVmAl8sVV3PzSh25Ew+e8CJhXoKxnbqQkpYF44yUKxBHAFL02sR8SpGCKaMebMeTKRuI3WLxaq00tNrPgGJoh90FZm1CIO+QS//dqc7XLfq3U1I3pacXhRwPqpjtPiAvVG2GbcIpiMid6KPiofRqJaYsowca2y67TOa7iatd68luwJq9UQeKbQgqXS0ynUYjuG7AlYXJIonyea63HYUyxRviMS+mrme3I38hBL9eqF/qzD1wVJtgoNfelm+aX07mJ/mcJNV5C/1/+B3fAnAD2J4NPQ+lAoCmPRxvrd+kMq0fhCUV4cI4I1L4XttpAr4gxUgUwHGLQ95xblQTv+zvrFYBjndzJFF7GX5m9MUdW1RaGmDNvN7JMA8l7xq4WZdy3oB7zPZb+uHKkjqM97P4n8G7NAI7aiBNAf46dxPBGM6XAdldqkfTGkdwBYkULRq1dS2FWK6OnnFVGenFv0="
      skip_cleanup: true
      on:
        all_branches: true
install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind ${EXTRA_OPAM}
- opam list
script:
- set -e
- echo 'Configuring Coq...' && echo -en 'travis_fold:start:coq.config\\r'
- "./configure ${COQ_DEST} -usecamlp5 -native-compiler ${NATIVE_COMP} ${EXTRA_CONF}"
- echo -en 'travis_fold:end:coq.config\\r'
- echo 'Building Coq...' && echo -en 'travis_fold:start:coq.build\\r'
- make -j ${NJOBS}
- echo -en 'travis_fold:end:coq.build\\r'
- echo 'Running tests...' && echo -en 'travis_fold:start:coq.test\\r'
- "${TW} make -j ${NJOBS} ${TEST_TARGET}"
- echo -en 'travis_fold:end:coq.test\\r'
- set +e
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3cdabdec318214c7cd63
    on_success: change
    on_failure: always
    on_start: never
